version: "3.9"

services:
  task-server:
    build:
      context: .
    container_name:
      task-server
    ports:
      - "8080:8080"
    networks:
      - mynet
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?database password not set}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=${POSTGRES_DB:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_SSLMODE=${POSTGRES_SSLMODE:-disable}
    depends_on:
      - postgres_db
    deploy:
      restart_policy:
        condition: on-failure
  postgres_db:
    hostname: db
    restart: always
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-qwerty}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5433:5432"
    networks:
      - mynet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynet:
    driver: bridge