version: "3.9"

services:
  task-server:
    build:
      context: .
    container_name:
      task-server
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
