basePath: /
definitions:
  main.RequestTask:
    properties:
      due:
        type: string
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /task/:
    post:
      description: Create one task
      parameters:
      - description: Add account
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/main.RequestTask'
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
      summary: Task
      tags:
      - Tasks
  /task/{id}:
    delete:
      description: delete one task
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
      summary: Task
      tags:
      - Tasks
    get:
      description: Get one task
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
      summary: Task
      tags:
      - Tasks
swagger: "2.0"
